### ISSUE TITLE
investigate and fix cmd unit tests

### ISSUE THREAD

**Issue by acharb** [stellar/stellar-etl#131]
some of the unit tests in cmd are failing, but I'm not sure if it's code we are still using. eg. `TestExportChanges/changes_from_single_ledger` using `export_ledger_entry_changes` (are we using this command anywhere?). Investigate if these command are something we still need and if so fix.

Once the `cmd` unit testing works we can add to the github workflow for automated testing ([pr](https://github.com/stellar/stellar-etl/pull/130) for reference)

**Comment by sydneynotthecity** [comment]
Fixed the export_transactions and export_operations tests. The other broken tests require a working captive core, which i'm still working on.

**Comment by sydneynotthecity** [comment]
@amishas157 we can close this ticket, correct? I believe https://github.com/stellar/stellar-etl/pull/274 resolved

**Comment by amishas157** [comment]
Yes., the docs for running tests are available in https://github.com/stellar/stellar-etl?tab=readme-ov-file#running-tests
