### ISSUE TITLE
Add feature for Exporter Interface(GCS, S3, Kafka and etc)

### ISSUE THREAD

**Issue by jensenity** [stellar/stellar-etl#197]
### What problem does your feature solve?
Reading the code for exporting the cmds, it only supports GCS for now. Since there are no export option interface, changing the export option for instance to S3 or to Kafka, or wanting to add a new feature has to change a lot of files and code.

### What would you like to see?
I will hope the exporting func are all abstracted into export and by default it will send the data to GCS, and we can start building S3, Kafka, Postgres exporters one by one.

### What alternatives are there?
Not for now

**Comment by sydneynotthecity** [comment]
@jensenity I agree this is a good feature. Once we are finished with the Protocol 20 testnet release, we will look into updating the code to an export interface versus the tight coupling with GCS today.

**Comment by chowbao** [comment]
Added flags and interface for choosing where to upload data
https://github.com/stellar/stellar-etl/blob/master/internal/utils/main.go#L253-L259
