### ISSUE TITLE
Map out account input and output data structures for CLI

### ISSUE THREAD

**Issue by Isaiah-Turner** [stellar/stellar-etl#23]
### What
We need to map out what information we get about accounts from the new ingestion system. We also need to know what the output to BigQuery should look like. Part of #19.

### Why
This issue helps us know what account information is easily accessible from the ingestion system and what information may have to be reconstructed or omitted.

**Comment by Isaiah-Turner** [comment]
There are two different ways to get the information on Accounts. The first is to use a LedgerTransactionReader and read
in Transactions one at a time. Then for each transaction, by looking at the Operations and their types, we can isolate what is relevant to accounts. The Operation types that affect accounts are: OperationTypeCreateAccount (0), OperationTypeAccountMerge (8), and possibly OperationTypeInflation (9). Keeping track of these operations would allow us to create a list of account operations and their timestamps. We also can use MakeSingleLedgerStateReader() to get the changes in a given ledger. Each change has a type, the relevant one being LedgerEntryTypeAccount. It also contains the LedgerEntry for before and after. This allows us to reconstruct the accounts table in BigQuery. For a given change of the correct type, we can do `acc := change.Post.Data.Account` to get account data in the ledger. In order reconstruct the table, we need a struct with the following fields:
```
account_id: string - get from acc.AccountId.GetAddress()
balance: signed 64 bit integer - get from acc.Balance
buying_liabilities: integer - In theory in acc.Ext.V1.Liabilities.Buying; not sure if implemented
selling_liabilities: integer - In theory in acc.Ext.V1.Liabilities.Selling; not sure if implemented
sequence_number: integer - get from acc.SeqNum
num_subentries: integer -  get from acc.NumSubEntries
inflation_destination: integer - get from acc.InflationDest.ToAccountId().GetAddress()
flags: integer - get from acc.Flags
home_domain: string - get from acc.HomeDomain
master_weight: integer - get from acc.MasterKeyWeight()
threshold_low: integer - get from acc.ThresholdLow()
threshold_medium: integer - get from acc.ThresholdMedium()
threshold_high: integer - get from acc.ThresholdHigh()
Last_modified_ledger: integer - get from change.Post.LastModifiedLedgerSeq

```

**Comment by debnil** [comment]
Awesome - like with [trustlines](https://github.com/stellar/stellar-etl/issues/28), we should enable both, so we have a more fine grained view of accounts.
