### ISSUE TITLE
Map out trustline input and output data structures for CLI

### ISSUE THREAD

**Issue by Isaiah-Turner** [stellar/stellar-etl#28]
### What
We need to map out what information we get about trustlines from the new ingestion system. We also need to know what the output to BigQuery should look like. Part of #19.

### Why
This issue helps us know what information about trustlines we can get from the ingestion system and what information may have to be reconstructed or omitted.

**Comment by Isaiah-Turner** [comment]
There are two different ways to get the information on Trustlines. The first is to use a LedgerTransactionReader and read
in Transactions one at a time. Then for each transaction, by looking at the Operations and their types, we can isolate what is relevant to trustlines. The Operation types that affect trustlines are: xdr.OperationTypeChangeTrust (6) and xdr.OperationTypeAllowTrust (7). Keeping track of these operations would allow us to create a list of trustline operations and their timestamps. We also can use MakeSingleLedgerStateReader() to get the changes in a given ledger. Each change has a type, the relevant one being LedgerEntryTypeTrustline. It also contains the LedgerEntry for before and after. This allows us to reconstruct the trustlines table in BigQuery. For a given change of the correct type, we can do 
`trust := change.Post.Data.TrustLine` to get trustline data in the ledger. In order reconstruct the table, we need a struct with the following fields:
```
ledger_key: string - use trustLineEntryToLedgerKeyString(trust) to get ledger_key
account_id: string - get from trust.AccountId.GetAddress()
asset: Asset struct - get from trust.Asset (has Type, AssetCode, Issuer)
balance: integer - get from trust.Balance
trust_line_limit: integer - get from trust.Limit
buying_liabilities: integer - In theory in trust.Ext.V1.Liabilities.Buying; not sure if implemented
selling_liabilities: integer - In theory in trust.Ext.V1.Liabilities.Selling; not sure if implemented
flags: integer - get from trust.Flags
last_modified_ledger: integer - get from change.Post.LastModifiedLedgerSeq
```
The [trustLineEntryToLedgerKeyString method](https://github.com/stellar/go/blob/954ddebed16bf9b0e44a610942725c6df53278cd/services/horizon/internal/db2/history/trust_lines.go) isn't exported. It creates an empty LedgerKey pointer, sets the key's trustline as the provided trustline, calls key.MarshalBinary(), and then base64.StdEncoding.EncodeToString(key).

**Comment by debnil** [comment]
Great find - we should do both in `export_trustlines`.  Probably want to add some flags/configuration to enable either or both. The default like should be both, since we'd just export serialized structs as documents, these then get written to BigQuery by a different stage of the pipeline.
